### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by chmma** [aletc1/examples-odata-azure-functions#2]
Hi, Nice work! But I've seen that in your repo there is no license file. Can I use your solution to my projects? Under what kind of license your code is? I know it's a little bit hacky, but I really like it! There is no official solution to use OData with Functions at the moment... Thanks

**Comment by aletc1** [comment]
Hi, Thanks. Sure, use it freely. I will update the LICENSE file to MIT. Thanks.
