### ISSUE TITLE
Random InvalidOperationException on function reload

### ISSUE THREAD

**Issue by jjavierdguezas** [aletc1/examples-odata-azure-functions#3]
We are using this example in our app and sometimes, after a function reload (due to a release for example) an `InvalidOperationException` is thrown

>Cannot find the services container for the non-OData route. This can occur when using OData components on the non-OData route and is usually a configuration issue. Call EnableDependencyInjection() to enable OData components on non-OData routes. This may also occur when a request was mistakenly handled by the ASP.NET Core routing layer instead of the OData routing layer, for instance the URL does not include the OData route prefix configured via a call to MapODataServiceRoute(). 

The ugly workaround is restart the azure function until this random error disappears

**Comment by jjavierdguezas** [comment]
Checking internet I found in a comment of [this StackOverflow answer](https://stackoverflow.com/a/45503102) the following
![image](https://user-images.githubusercontent.com/13673443/89634901-722ddb00-d8a6-11ea-9076-7998ef57d052.png)

We made the changes suggested on https://github.com/Microsoft/aspnet-api-versioning/issues/361#issuecomment-427679607 and the issue seems to go away.
I opened this issue to track this problem, and to let you review all my findings. If in a few days this problem does not appear again and you agree, I'll be more that happy to do a PR

**Comment by aletc1** [comment]
Sure @jjavierdguezas, be my guest and send a pull request. 
Regarding v3 (.NET Core 3.1 and v3 Functions), it might not be necessarily to disable Endpoint routing nor enabling dependency injection. This should work (I have tested it already in ASP.NET Core 3, but not yet in v3 function): https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/
